//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldOfDiscs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public Feedback()
        {
            this.ReplyFeedbacks = new HashSet<ReplyFeedback>();
        }
    
        public int Id { get; set; }
        public int Id_User { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<ReplyFeedback> ReplyFeedbacks { get; set; }
    }
}
