//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldOfDiscs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Category
    {
        public Group_Category()
        {
            this.Categories = new HashSet<Category>();
            this.Discs = new HashSet<Disc>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Disc> Discs { get; set; }
    }
}
