//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldOfDiscs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disc
    {
        public Disc()
        {
            this.Detail_Order = new HashSet<Detail_Order>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Actor { get; set; }
        public string Country { get; set; }
        public string Type { get; set; }
        public string Image_small { get; set; }
        public string Image_big { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Id_Category { get; set; }
        public Nullable<int> Id_Group_Category { get; set; }
        public Nullable<int> IsNew { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Detail_Order> Detail_Order { get; set; }
        public virtual Group_Category Group_Category { get; set; }
    }
}
