//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldOfDiscs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum_Comment
    {
        public int Id { get; set; }
        public Nullable<int> Id_Forum_Post { get; set; }
        public Nullable<int> Id_User { get; set; }
        public string Content { get; set; }
    
        public virtual Forum_Post Forum_Post { get; set; }
        public virtual User User { get; set; }
    }
}
