//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldOfDiscs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Detail_Order = new HashSet<Detail_Order>();
            this.Direct_Payment_Method = new HashSet<Direct_Payment_Method>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_User { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Id_Payment_Method { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> IsPaid { get; set; }
    
        public virtual ICollection<Detail_Order> Detail_Order { get; set; }
        public virtual Payment_Method Payment_Method { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Direct_Payment_Method> Direct_Payment_Method { get; set; }
    }
}
