//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldOfDiscs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Forum_Comment = new HashSet<Forum_Comment>();
            this.Forum_Post = new HashSet<Forum_Post>();
            this.Orders = new HashSet<Order>();
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Sex { get; set; }
        public string Avatar { get; set; }
        public string Password { get; set; }
        public Nullable<int> isAdmin { get; set; }
    
        public virtual ICollection<Forum_Comment> Forum_Comment { get; set; }
        public virtual ICollection<Forum_Post> Forum_Post { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
