//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldOfDiscs.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorldOfDiscsEntities : DbContext
    {
        public WorldOfDiscsEntities()
            : base("name=WorldOfDiscsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Detail_Order> Detail_Order { get; set; }
        public virtual DbSet<Direct_Payment_Method> Direct_Payment_Method { get; set; }
        public virtual DbSet<Disc> Discs { get; set; }
        public virtual DbSet<Forum_Comment> Forum_Comment { get; set; }
        public virtual DbSet<Forum_Post> Forum_Post { get; set; }
        public virtual DbSet<Group_Category> Group_Category { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Payment_Method> Payment_Method { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<ReplyFeedback> ReplyFeedbacks { get; set; }
    }
}
